version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=magazord
    ports:
      - "5432:5432"
  api:
    build:
      dockerfile: Dockerfile
      context: "./maga-back"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - /maga-back/vendor
    environment:
      - PGUSER=postgres
      - PGHOST=localhost
      - PGDATABASE=magazord
      - PGPASSWORD=postgres
      - PGPORT=5432
  client:
    stdin_open: true
    depends_on:
      - postgres
      - api
    build:
      dockerfile: Dockerfile
      context: ./maga-front
    ports:
      - "3000:3000"
    volumes:
      - /maga-front/node_modules