version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      dockerfile: Dockerfile
      context: "./maga-back"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - /maga-back/vendor
    environment:
      - PGUSER=postgres
      - PGHOST=localhost
      - PGDATABASE=maga
      - PGPASSWORD=postgres
      - PGPORT=5455
  client:
    stdin_open: true
    depends_on:
      - postgres
      - api
    build:
      dockerfile: Dockerfile
      context: ./maga-front
    volumes:
      - /maga-front/node_modules